### ISSUE TITLE
Google Endpoints Backend deployen

### ISSUE THREAD

**Issue by simonmeier** [itcc-li/hackathon2015-android#7]
Innerhalb des -android Projekts gibt es ein Backend Modul. Dieses kompiliert im Ordner build/app-exploded basiert gemäss Arthur auf Java Servlets und kann auf einem Tomcat Server deployed werden. Wir können gerne einen TomCat Server auf der 2. Instanz (Ubuntu Servers) meines Amazon Web Service Accounts erstellen und dort das Backend deployen.

**Comment by bluehack42** [comment]
Ich habe einen Tomcat auf Debian basis am laufen. Der blog laeuft schon auf diesem. Aber coole idee!
